### ISSUE TITLE
InvalidCastException when using the coin

### ISSUE THREAD

**Issue by SHTLUOLEI** [Mikihero/BetterCoinflips#5] opened 2023-01-11 17:26 UTC
When I successfully generated dll and ran it, I found a random error. I don't know what the error is, because I am a plug-in beginner, so I would like to ask you to help me fix it. Thank you
![Screenshot 2023-01-12 012536](https://user-images.githubusercontent.com/112939682/211874765-f17b90ba-b25b-4720-8e97-df8428608496.png)

**Comment by Mikihero** [comment] 2023-01-11 21:31
The plugin doesn't yet have a release because all I did was get the plugin to compile, once I test everything, and decide how I wanna deal with some problems etc. the plugin will be released. That said this should be a pretty easy fix, one of my casts is just incorrect so fixing it won't be too hard. Also even tho the plugin is not yet release for 6.0 I really appreciate the feedback. One last question: what system are using? (linux/windows) If you're using linux, Did you encounter any errors while loading the plugin? And where are you hosting your server? Is it a vps, a hosting or perhaps your own machine? All that info would be really helpful in identifying an old bug that no one really understood if it were to reappear.

**Comment by Mikihero** [comment] 2023-01-11 22:28
Good news: I've found the bug
Bad news: It's an EXILED issue with a cast in GrenadePickup or smth
Good news: It might be fixed in beta21 which is supposed to release very soon
PS: I'd still be very grateful if you answered my last few questions from the message above, thank you in advance.

**Comment by SHTLUOLEI** [comment] 2023-01-12 07:15
I use the windows system of win11, the server is running on my own machine
![Screenshot 2023-01-12 151230](https://user-images.githubusercontent.com/112939682/212001167-6dbc3cb8-956f-44a4-b1c0-348205426bf0.png)
The console didn't report any errors when the plugin was loading, but when I used the coin, normally, random success didn't have a coin flip. But sometimes there will be a normal coin flip, and the console will report an error, which is the error we gave you before
I am not good at English, these are translated into English by software, there may be some reading problems, sorry

**Comment by Mikihero** [comment] 2023-01-12 10:46
As I said, the bug is caused by EXILED itself and will be fixed whenever beta21 is released (which shouldn't take too long from now)

**Comment by SHTLUOLEI** [comment] 2023-01-12 11:11
Ok, thank you. The coin random plugin has taught me a lot as a beginner

**Closed** 2023-04-14 15:08 UTC
Labels: exiled issue
